name: CI
on:
  schedule:
    - cron: '31 12 * * *'
    - cron: '12 17 * * *'
    
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
    - run: npm install
    - name: Test Code
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: node bot.js
